name: 'tv_shows_dbt'
version: '1.0.0'
config-version: 2

profile: 'tv_shows_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tv_shows_dbt:
    staging:
      +materialized: table
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
    reporting:
      +materialized: table
      +schema: reporting

