tv_shows_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('NEON_HOST') }}"
      user: "{{ env_var('NEON_USER') }}"
      password: "{{ env_var('NEON_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('NEON_DATABASE') }}"
      schema: staging
      threads: 4
      sslmode: require

